version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: gestiune
      POSTGRES_USER: gestiune
      POSTGRES_PASSWORD: gestiune
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
